name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4  

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm test:panel

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    concurrency: "run"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

     
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build App
        run: |
          pnpm build:panel
      - name: Copy Readme
        run: |
          pnpm cpy:readme
      - name: Publish with pnpm
        run: |
          cd packages/trpc-ui
          echo "publishing with version ${{ github.event.release.tag_name }}"
          pnpm publish --access public --new-version ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
